
dropdown_options = [
    {'label': 'AAPL', 'value': 'AAPL'},
    {'label': 'META', 'value': 'META'},
    {'label': 'GOOG', 'value': 'GOOG'},
    {'label': 'AMZN', 'value': 'AMZN'},
    {'label': 'MSFT', 'value': 'MSFT'},
    {'label': 'NVDA', 'value': 'NVDA'},
    {'label': 'NDX', 'value': 'NDX'},
    {'label': 'QQQ', 'value': 'QQQ'},
    {'label': '^SPX', 'value': '^SPX'},
    {'label': 'INDY', 'value': 'INDY'},
    {'label': 'TSLA', 'value': 'TSLA'},
    {'label': 'KWEB', 'value': 'KWEB'},
    {'label': 'GLD', 'value': 'GLD'},
    {'label': 'SLV', 'value': 'SLV'},
    {'label': 'SOXX', 'value': 'SOXX'},
    {'label': 'IHI', 'value': 'IHI'},
    {'label': 'NFLX', 'value': 'NFLX'},
    {'label': 'DIS', 'value': 'DIS'},
    {'label': 'BTC-USD', 'value': 'BTC-USD'},
    {'label': '^TNX', 'value': '^TNX'},
    {'label': '^DJI', 'value' : '^DJI'},
    {'label': '^GSPC', 'value' : '^GSPC'},
    {'label': '^NDX', 'value' : '^NDX'},
]
